### ISSUE TITLE
linked files are not being created

### ISSUE THREAD

**Issue by andywenk** [runar/capistrano-linked-files#4]
Hi,

first off all thanks a lot for this nice piece of software ;-). I like it a lot cuz it's makes our life easier ;-).

I recognised, that `cap stage deploy:check:linked_files` is not working, when the files do not exist. 

```
DEBUG [f71f7918] Finished in 0.129 seconds with exit status 1 (failed).
ERROR linked file /var/www/stage/shared/config/database.yml does not exist on IP
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as syncrobot@IP: exit

SystemExit: exit
```

Do I misunderstand sth.? I guess this is easily fixable ...

All the best

Andy

**Comment by btc** [comment]
To upload files, you need to execute:

```
bundle exec cap <STAGE> linked_files:upload_files
```

**Comment by jun1st** [comment]
after add the gem to Gemfile,

I got

> Don't know how to build task 'linked_files:upload_files'

**Comment by zhisme** [comment]
@jun1st  add this to `config/deploy.rb`
```
# Uploading both linked_files and dirs
before 'deploy:check:linked_files', 'linked_files:upload'
```

**Comment by borenho** [comment]
This doesn't work, @zhisme . Getting an exception `Don't know how to build task 'linked_files:upload'`. Does it come with the gem or we have to define the task somewhere?
